import type { BankOption } from '../types/payroll';

export const BANKS: BankOption[] = [
  { bank_name: 'anz indonesia', bank_code: 'bank_anz' },
  { bank_name: 'bank aladin syariah', bank_code: 'bank_aladin' },
  { bank_name: 'bank antardaerah', bank_code: 'bank_antardaerah' },
  { bank_name: 'bpd diy syariah', bank_code: 'bank_daerah_istimewa_syr' },
  { bank_name: 'tmrw/uob', bank_code: 'bank_uob' },
  { bank_name: 'billfazz', bank_code: 'bank_billfazz' },
  { bank_name: 'panin dubai syariah', bank_code: 'bank_panin_syr' },
  { bank_name: 'nobu (nationalnobu) bank', bank_code: 'bank_nationalnobu' },
  { bank_name: 'bank mayapada', bank_code: 'bank_mayapada' },
  { bank_name: 'bank aceh syariah', bank_code: 'bank_aceh' },
  { bank_name: 'bri', bank_code: 'bank_bri' },
  { bank_name: 'bank danamon syariah', bank_code: 'bank_danamon_syr' },
  { bank_name: 'line bank/keb hana', bank_code: 'bank_hana' },
  { bank_name: 'bank riau kepri', bank_code: 'bank_riau_dan_kepri' },
  { bank_name: 'atmb lsb (bpr lsb)', bank_code: 'bank_atmb_lsb' },
  { bank_name: 'standard chartered bank', bank_code: 'bank_standard_chartered' },
  { bank_name: 'bank jatim syariah', bank_code: 'bank_jawa_timur_syr' },
  { bank_name: 'bank ibk indonesia', bank_code: 'bank_agris' },
  { bank_name: 'bank shinhan indonesia', bank_code: 'bank_shinhan' },
  { bank_name: 'bank kaltimtara', bank_code: 'bank_kalimantan_timur' },
  { bank_name: 'bank kaltimtara syariah', bank_code: 'bank_kalimantan_timur_syr' },
  { bank_name: 'bank dki syariah', bank_code: 'bank_dki_syr' },
  { bank_name: 'bnp paribas indonesia', bank_code: 'bank_bnp_paribas' },
  { bank_name: 'bjb syariah', bank_code: 'bank_bjb_syr' },
  { bank_name: 'bank bukopin syariah', bank_code: 'bank_bukopin_syr' },
  { bank_name: 'bank mutiara', bank_code: 'bank_mutiara' },
  { bank_name: 'bank amar indonesia', bank_code: 'bank_amar' },
  { bank_name: 'icbc indonesia', bank_code: 'bank_icbc' },
  { bank_name: 'kc jpmorgan chase bank', bank_code: 'bank_jpmorgan_chase' },
  { bank_name: 'bank of america na', bank_code: 'bank_america_na' },
  { bank_name: 'bni', bank_code: 'bank_bni' },
  { bank_name: 'bank china construction bank indonesia', bank_code: 'bank_ccb' },
  { bank_name: 'bank ntt', bank_code: 'bank_nusa_tenggara_timur' },
  { bank_name: 'sakuku', bank_code: 'bank_sakuku' },
  { bank_name: 'dompetku', bank_code: 'bank_dompetku' },
  { bank_name: 'bank victoria international', bank_code: 'bank_victoria_internasional' },
  { bank_name: 'bank sumut', bank_code: 'bank_sumut' },
  { bank_name: 'bank of india indonesia', bank_code: 'bank_india' },
  { bank_name: 'bpr eka (bank eka)', bank_code: 'bank_eka' },
  { bank_name: 'bca', bank_code: 'bank_bca' },
  { bank_name: 'bank mestika dharma', bank_code: 'bank_mestika_dharma' },
  { bank_name: 'bank ganesha', bank_code: 'bank_ganesha' },
  { bank_name: 'ocbc nisp syariah', bank_code: 'bank_ocbc_syr' },
  { bank_name: 'bank multi arta sentosa (bank mas)', bank_code: 'bank_mas' },
  { bank_name: 'bank mega', bank_code: 'bank_mega' },
  { bank_name: 'maybank indonesia syariah', bank_code: 'bank_bii_syr' },
  { bank_name: 'bsi (bank syariah indonesia)', bank_code: 'bank_bsm' },
  { bank_name: 'bpd banten', bank_code: 'bank_banten' },
  { bank_name: 'bank kalbar syariah', bank_code: 'bank_kalimantan_barat_syr' },
  { bank_name: 'blu/bca digital', bank_code: 'bank_royal' },
  { bank_name: 'bank ntb syariah', bank_code: 'bank_nusa_tenggara_barat' },
  { bank_name: 'bank sumbar (bank nagari)', bank_code: 'bank_sumatera_barat' },
  { bank_name: 'wokee/bukopin', bank_code: 'bank_bukopin' },
  { bank_name: 'bank mayora indonesia', bank_code: 'bank_mayora' },
  { bank_name: 'bank dki jakarta', bank_code: 'bank_dki' },
  { bank_name: 'e2pay', bank_code: 'bank_e2pay' },
  { bank_name: 'danamon / danamon syariah', bank_code: 'bank_danamon' },
  { bank_name: 'bank prima master', bank_code: 'bank_prima' },
  { bank_name: 'bpd diy', bank_code: 'bank_daerah_istimewa' },
  { bank_name: 'bank maspion indonesia', bank_code: 'bank_maspion' },
  { bank_name: 'bank permata', bank_code: 'bank_permata' },
  { bank_name: 'motion/mnc bank', bank_code: 'bank_mnc_internasional' },
  { bank_name: 'hsbc indonesia', bank_code: 'bank_hsbc' },
  { bank_name: 'bank sumsel babel syariah', bank_code: 'bank_sumsel_dan_babel_syr' },
  { bank_name: 'bank bengkulu', bank_code: 'bank_bengkulu' },
  { bank_name: 'bank capital indonesia', bank_code: 'bank_capital' },
  { bank_name: 'bank sulutgo', bank_code: 'bank_sulut' },
  { bank_name: 'dutamoney', bank_code: 'bank_dutamoney' },
  { bank_name: 'bank sinarmas', bank_code: 'bank_sinarmas' },
  { bank_name: 'bank victoria syariah', bank_code: 'bank_victoria_syr' },
  { bank_name: 'bank mega syariah', bank_code: 'bank_mega_syr' },
  { bank_name: 'bank sulselbar syariah', bank_code: 'bank_sulselbar_syr' },
  { bank_name: 'midtrans', bank_code: 'bank_midtrans' },
  { bank_name: 'maybank indonesia', bank_code: 'bank_bii' },
  { bank_name: 'bank kalsel syariah', bank_code: 'bank_kalimantan_selatan_syr' },
  { bank_name: 'bank jambi syariah', bank_code: 'bank_jambi_syr' },
  { bank_name: 'panin bank', bank_code: 'bank_panin' },
  { bank_name: 'bank btpn syariah', bank_code: 'bank_btpn_syr' },
  { bank_name: 'bank sulselbar', bank_code: 'bank_sulselbar' },
  { bank_name: 'bank sumsel babel', bank_code: 'bank_sumsel_dan_babel' },
  { bank_name: 'bank maluku', bank_code: 'bank_maluku' },
  { bank_name: 'bank kalbar', bank_code: 'bank_kalimantan_barat' },
  { bank_name: 'commonwealth bank', bank_code: 'bank_commonwealth' },
  { bank_name: 'ocbc nisp', bank_code: 'bank_ocbc' },
  { bank_name: 'sbi indonesia', bank_code: 'bank_sbi_indonesia' },
  { bank_name: 'neo commerce/yudha bhakti', bank_code: 'bank_yudha_bakti' },
  { bank_name: 'bank nagari syariah', bank_code: 'bank_sumatera_barat_syr' },
  { bank_name: 'cimb niaga/cimb niaga syariah', bank_code: 'bank_cimb' },
  { bank_name: 'dbs indonesia', bank_code: 'bank_dbs' },
  { bank_name: 'citibank', bank_code: 'bank_citibank' },
  { bank_name: 'bank sultra', bank_code: 'bank_sulawesi_tenggara' },
  { bank_name: 'bank kalteng', bank_code: 'bank_kalimantan_tengah' },
  { bank_name: 'bank woori saudara', bank_code: 'bank_woori' },
  { bank_name: 'bank sahabat sampoerna', bank_code: 'bank_sahabat_sampoerna' },
  { bank_name: 'bjb', bank_code: 'bank_bjb' },
  { bank_name: 'bank mantap (mandiri taspen)', bank_code: 'bank_mantap' },
  { bank_name: 'bank nusantara parahyangan', bank_code: 'bank_nusantara_parahyangan' },
  { bank_name: 'bank of tokyo mitsubishi ufj', bank_code: 'bank_tokyo' },
  { bank_name: 'bank sulteng', bank_code: 'bank_sulawesi' },
  { bank_name: 'btn syariah', bank_code: 'bank_btn_syr' },
  { bank_name: 'btn', bank_code: 'bank_btn' },
  { bank_name: 'atmb plus', bank_code: 'bank_atmb_plus' },
  { bank_name: 'bank mizuho indonesia', bank_code: 'bank_mizuho' },
  { bank_name: 'bank jatim', bank_code: 'bank_jawa_timur' },
  { bank_name: 'rabobank international indonesia', bank_code: 'bank_rabobank' },
  { bank_name: 'bank papua', bank_code: 'bank_papua' },
  { bank_name: 'bank artha graha internasional', bank_code: 'bank_artha' },
  { bank_name: 'bank bumi arta', bank_code: 'bank_bumi_arta' },
  { bank_name: 'allo bank/bank harda internasional', bank_code: 'bank_harda' },
  { bank_name: 'bank sinarmas syariah', bank_code: 'bank_sinarmas_syr' },
  { bank_name: 'btpn / jenius / btpn wow!', bank_code: 'bank_tabungan_pensiunan_nasional' },
  { bank_name: 'qnb indonesia', bank_code: 'bank_qnb_kesawan' },
  { bank_name: 'jago/artos', bank_code: 'bank_artos' },
  { bank_name: 'bank sumut syariah', bank_code: 'bank_sumut_syr' },
  { bank_name: 'tokopedia', bank_code: 'bank_tokopedia' },
  { bank_name: 'permata syariah', bank_code: 'bank_permata_syr' },
  { bank_name: 'bank cnb (centratama nasional bank)', bank_code: 'bank_cnb' },
  { bank_name: 'bank jambi', bank_code: 'bank_jambi' },
  { bank_name: 'finnet', bank_code: 'bank_finnet' },
  { bank_name: 'saldo flip', bank_code: 'bank_saldo_flip' },
  { bank_name: 'bank ina perdana', bank_code: 'bank_ina_perdana' },
  { bank_name: 'ctbc (chinatrust) indonesia', bank_code: 'bank_chinatrust' },
  { bank_name: 'bank jago syariah', bank_code: 'bank_artos_syr' },
  { bank_name: 'bpd bali', bank_code: 'bank_bali' },
  { bank_name: 'bank index selindo', bank_code: 'bank_index_selindo' },
  { bank_name: 'bank jateng syariah', bank_code: 'bank_jawa_tengah_syr' },
  { bank_name: 'bank dinar indonesia', bank_code: 'bank_dinar' },
  { bank_name: 'muamalat', bank_code: 'bank_muamalat' },
  { bank_name: 'bank resona perdania', bank_code: 'bank_resona_perdania' },
  { bank_name: 'bank jateng', bank_code: 'bank_jawa_tengah' },
  { bank_name: 'bank of china (hong kong) limited', bank_code: 'bank_boc' },
  { bank_name: 'bank lampung', bank_code: 'bank_lampung' },
  { bank_name: 'bank kalsel', bank_code: 'bank_kalimantan_selatan' },
  { bank_name: 'mandiri', bank_code: 'bank_mandiri' },
  { bank_name: 'bank jasa jakarta', bank_code: 'bank_jasa_jakarta' },
  { bank_name: 'bri agroniaga', bank_code: 'bank_agroniaga' },
  { bank_name: 'seabank/bank bke', bank_code: 'bank_kesejahteraan_ekonomi' },
  { bank_name: 'bca (bank central asia) syariah', bank_code: 'bank_bca_syr' },
];
